### PR TITLE
Api get gallery

### PR DESCRIPTION
**Pull request by xavier-fenton**

### CODE REVIEW

**Review by ford-jones — CHANGES_REQUESTED** [review]
Great work on the keys here bud. 
Would you mind changing the name of this api file from `shopGallery.js` to `gallery.js` ? 
This api call is unrelated to any shop data, the gallery is its' own area.

**Comment by xavier-fenton** [comment]
can u review this now?

**Review by ford-jones — APPROVED** [review]
Beast mode

**Comment by xavier-fenton** [comment]
beast mode

**Pull request merged**
